### ISSUE TITLE
Unnecessary mbmisc dependency 

### ISSUE THREAD

**Issue by malcolmbarrett** [rmetaverse/metaverse#18]
metaverse currently depends on my mbmisc package, but I don't think it's necessary (and it may not be a good idea anyway, because I'm not sure mbmisc will ever end up on CRAN). The article on meta-analysis workflow also loads that package but doesn't seem to use it.

**Comment by kylehamilton** [comment]
This may be the fastest fix I'll ever make. Done and done!

**Comment by malcolmbarrett** [comment]
ha nice! it's also in the vignette I mentioned

**Comment by malcolmbarrett** [comment]
(that also might be the fastest I've ever had an issue fixed 😉)

**Comment by kylehamilton** [comment]
I'm gonna go through that and give it a bit of an overhaul later when I have some free time. I'll make sure to add that to my list of things to keep an eye out for because I know I'll forget about it.
